version: '3.9'

x-develop: &default-develop
  watch:
    - action: sync
      path: ./data
      target: /app/data

    - action: sync
      path: ./public
      target: /app/public

    - action: sync
      path: ./src
      target: /app/src

    - action: sync
      path: ./config
      target: /app/config

    - action: sync
      path: ./notebooks
      target: /app/notebooks

    - action: sync
      path: ./visualization
      target: /app/visualization

    - action: sync
      path: ./vendor
      target: /app/vendor

services:
  app:
    build:
      context: .
      target: builder
    container_name: app
    working_dir: /app
    ports:
      - "8501:8501"
    stdin_open: true
    tty: true
    develop:
      <<: *default-develop
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: >
      streamlit run public/app.py --server.port=8501 --server.address=0.0.0.0

  #=================================================   jupyter ==================
  jupyter:
    image: jupyter/datascience-notebook:python-3.11
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      db:
        condition: service_healthy
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    env_file:
      - .env
    restart: unless-stopped

  #=================================================   data base ==================
  db:
    image: postgres:15-alpine # Lighter image
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  #=================================================   data base ==================
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin_data:
